### ISSUE TITLE
resource leak due to health check

### ISSUE THREAD

**Issue by KBorm** [uni-halle/maximapool-docker#10]
I had to disable health check in Dockerfile because the server does not respond anymore after about an hour. CPU load is more than 100% (top). After disabling health check everything is fine.

**Comment by Rillke** [comment]
Confirmed. The Java application is creating threads which are never ended. Thanks for reporting.

Thread dump:
https://pastebin.ubuntu.com/p/Jwzgm83k3p/

Threads like
```
"http-nio-8080-exec-10-reader" #137 daemon prio=5 os_prio=0 cpu=11435.26ms elapsed=316.25s tid=0x00007f9618003800 nid=0x1c5 sleeping [0x00007f95fa0e3000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(java.base@11.0.1/Native Method)
	at java.lang.Thread.sleep(java.base@11.0.1/Thread.java:339)
	at fi.aalto.utils.ReaderSucker$1.run(ReaderSucker.java:66)
```

On exit:
https://pastebin.ubuntu.com/p/f3TRmgDTyq/

```
26-Jul-2019 08:28:58.324 WARNING [Thread-4] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [MaximaPool] appears to have started a thread named [http-nio-8080-exec-1-reader] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.1/java.lang.Thread.sleep(Native Method)
 java.base@11.0.1/java.lang.Thread.sleep(Thread.java:339)
 fi.aalto.utils.ReaderSucker$1.run(ReaderSucker.java:66)
```

**Comment by Rillke** [comment]
Seems to be caused by invoking the low level health check. Going to disable that for now. And report upstream.

**Comment by pawohl** [comment]
@KBorm The develop and stack-2018080600 branches produced new images on Docker Hub. In order to get those, use `docker pull unihalle/maximapool:latest` or `docker pull unihalle/maximapool:stack-2018080600` respectively. Please let me know if there are more issues.
