### ISSUE TITLE
When is upgrade to qtype_stack 4.2.2 ?

### ISSUE THREAD

**Issue by jarvil1** [uni-halle/maximapool-docker#11]
Hello,

When are you upgrading stack to new qtype_stack 4.2.2 version in this project? And when you do update it when it will available at https://hub.docker.com/r/unihalle/maximapool ?

**Comment by Rillke** [comment]
Hi @Urpokarhu1 Uni Halle only supports me for ILIAS related-work. While I happily review, merge and publish your pull requests for Moodle, I cannot test in Moodle myself.

**Comment by Rillke** [comment]
Drafting an update right now. When ready, can you please test it for me?

**Comment by Rillke** [comment]
@Urpokarhu1 new image has been published. Please test, especially the plots and if you can the `simplex` package.
If everything works, please close this issue.

**Comment by Rillke** [comment]
@Urpokarhu1 If you depend on and have trouble maintaining this docker image yourself, we [maybe](https://wohlpa.de/#contact) can agree on a service contract for the Moodle part.
