### ISSUE TITLE
Please could you upgrade to qtype_stack 4.3.1 ?

### ISSUE THREAD

**Issue by mwuttke** [uni-halle/maximapool-docker#12]
Hello @Rillke ,

please cloud you upgrade docker image for stack to the new qtype_stack 4.3.1 version for our moodle useres? We are using your docker image for maximapool at https://hub.docker.com/r/unihalle/maximapool for our setup. It would be really nice if could update the docker image.

Thanks & Greetings,
Michael

**Comment by Rillke** [comment]
@moodlebeuth Docker Images are building. Please test them when finished. If something does not work as expected, re-open this issue.
