### ISSUE TITLE
Mount point means the pool.conf cannot be edited

### ISSUE THREAD

**Issue by marcusgreen** [uni-halle/maximapool-docker#15]
This is probably more about documentation or my understanding than an actual bug, but ...

If I follow the suggestion to use the following mount line in the docker run command

  -v "/path/to/volumes/pool.conf:/opt/maximapool/pool.conf:ro" \

This mounts pool.conf  as a folder so I get an error when docker starts as it is expecting to see a text file called
pool.conf
Whereas pool.conf is a folder.

The (500) error message from the browser is
Configuation file /opt/maximapool/pool.conf does not exist.

And the log shows as follows

Missing /opt/maximapool/pool.conf
Please edit volumes/pool.conf.template
and mount that or a copy of it to
/opt/maximapool/pool.conf

I can get around this by removing the mount line and copying into the container like this.
docker cp pool.conf MaximaPool:/opt/maximapool
But I'd like to know how/if I could mount as per the instructions.

**Comment by Rillke** [comment]
The first step in #usage is to create the `volumes/pool.conf` file. When you create this file, and mount it, it will be a file mount, not a directory.

**Comment by Rillke** [comment]
n.b. if the file does not exist, docker automatically tries to create a directory for you

**Comment by marcusgreen** [comment]
My apologies, there was clearly a problem between the keyboard and chair :(. The instructions are quite clear. I have it working now. Thank you for your quick response.
