### ISSUE TITLE
Please could you provide a docker image for stack 4.3.8?

### ISSUE THREAD

**Issue by mwuttke** [uni-halle/maximapool-docker#16]
Hello,

please cloud you provide a docker image for the stack version 4.3.8, so we could install the qtype_stack 4.3.8 version for our moodle useres? This would be really nice.

Thanks a lot in advance,
Michael

**Comment by harriholappa** [comment]
@Rillke Hello, are there any plans to provide a docker image for STACK 4.3.8?

**Comment by mwuttke** [comment]
@harriholappa Please have a look at the [README.md](https://github.com/uni-halle/maximapool-docker#the-future). ;-)

Michael
