### ISSUE TITLE
Updated builds?

### ISSUE THREAD

**Issue by marxjohnson** [uni-halle/maximapool-docker#5]
I'm currently looking at using docker images for our (Open University) automated testing setup.
We currently have the following STACK versions running which we'd like to be able to test against, and we update regularly:
2017060600
2018030500
2018080600

Are you planning to continue maintaining this docker image and publishing builds for more recent versions of STACK, or should I be looking at doing this myself?

**Comment by Rillke** [comment]
> Are you planning to continue maintaining this docker image and publishing builds for more recent versions of STACK, or should I be looking at doing this myself?

I greatly appreciate pull requests. I can only allocate time for these images either by reviewing pull requests or when uni-halle needs an update. Otherwise I have to spend spare time, which I am running out of.

**Comment by marxjohnson** [comment]
Thanks, so as an example, if I created pull requests to include the appropriate version of moodle-qtype_stack for each of the versions we'd like to test against, would you be able to build and publish these images?  
I'm fairly new to Docker, but from looking at Docker Hub it seems that the build and publish process is fairly automated once its pushed to GitHub?

**Comment by Rillke** [comment]
> Thanks, so as an example, if I created pull requests to include the appropriate version of moodle-qtype_stack for each of the versions we'd like to test against, would you be able to build and publish these images?

The git branches are mapped to docker hub tags.

> the build and publish process is fairly automated once its pushed to GitHub

That's the plan. Some work might be required to get builds for both, moodle and ILIAS, but it's enough if you only care for moodle and leave the ILIAS plug-in and ILIAS-related documentation untouched.

For that to work, replace `ARG BUILD_FOR_MOODLE` with `ARG BUILD_FOR_MOODLE=true` in the Docker file, update the git submodule assets/stack_util_maximapool and follow [#contributing](https://github.com/uni-halle/maximapool-docker/blob/develop/README.md#contributing) in README.md

For more questions, please do not hesitate asking.
